services:
  bc:
    build:
      context: .
      dockerfile: dockerfile-wine-custom
      args:
        BUILDKIT_PROGRESS: plain  # Show full build output
    environment:
      - SA_PASSWORD=${SA_PASSWORD:-P@ssw0rd123!}
      - SQL_SERVER=${SQL_SERVER:-external-sql-server}
      - SQL_SERVER_PORT=${SQL_SERVER_PORT:-1433}
      - BC_AUTOSTART=false
    ports:
      - "7046:7046"  # BC OData
      - "7047:7047"  # BC SOAP
      - "7048:7048"  # BC Management
      - "7049:7049"  # BC Development
    volumes:
      - bc_data:/home/bcserver
      - bc_artifacts:/home/bcartifacts
      - wine_data:/root/.wine
      - wine_cache:/ccache  # Cache compiler output for faster rebuilds
    networks:
      - bc-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'Microsoft.Dynamics.Nav.Server.exe' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 300s  # Give more time for Wine initialization

volumes:
  bc_data:
    driver: local
  bc_artifacts:
    driver: local
  wine_data:
    driver: local
  wine_cache:
    driver: local

networks:
  bc-network:
    driver: bridge